winscholarship/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('post','PostController');
Route::resource('lookups','LookupsController');

Route::get('postdisplay','PostController@display');

winscholarship/app/Lookups.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lookups extends Model
{
    protected $fillable=
    [
        'name'
    ];

}

winscholarship/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

winscholarship/app/post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class post extends Model
{
    protected $fillable=['body','title','fb_link','end_date','location_id','field_of_study_id','study_level_id','english_requirment_id','abroad'];
    

    public function location()
    {								
        return $this->belongsTo('App\Lookups', 'location_id');
    }

    public function field()
    {								
        return $this->belongsTo('App\Lookups', 'field_of_study_id');
    }

    public function level()
    {								
        return $this->belongsTo('App\Lookups', 'study_level_id');
    }

    public function english()
    {								
        return $this->belongsTo('App\Lookups', 'english_requirment_id');
    }
    

    
}

winscholarship/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

winscholarship/app/Http/Controllers/LookupsController.php
<?php

namespace App\Http\Controllers;

use App\Lookups;
use Illuminate\Http\Request;

class LookupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $lookups=lookups::get();
        return response()->view('lookups\table',['post'=>$lookups]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lookups_cat=lookups::where('cat_id',null)->get();
        $lookups=lookups::get();


        return response()->view('lookups\add',['lookups_cat'=>$lookups_cat,'lookups'=>$lookups]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        lookups::create($request->only(['name','parent_id','cat_id']));
        return $this->index();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lookups  $lookups
     * @return \Illuminate\Http\Response
     */
    public function show(Lookups $lookups)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lookups  $lookups
     * @return \Illuminate\Http\Response
     */
    public function edit(Lookups $lookups)
    {
        return response()->view('lookups\edit',['lookup'=>$lookups]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lookups  $lookups
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lookups $lookups)
    {
        $lookups->update($request->all());
        return $this->index();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lookups  $lookups
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lookups $lookups)
    {
        $lookups->delete();
        return $this->index();
    }
}

winscholarship/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\post;
use App\lookups;
use Illuminate\Http\Request;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post=post::get();
        return response()->view('post\table',['post'=>$post]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lookups_loc=lookups::where('cat_id',1)->get();
        $lookups_level=lookups::where('cat_id',2)->get();
        $lookups_field=lookups::where('cat_id',3)->get();
        $lookups_req=lookups::where('cat_id',4)->get();
        return response()
        ->view('post\add',
        ['lookups_loc'=>$lookups_loc,'lookups_level'=>$lookups_level,
        'lookups_field'=>$lookups_field,'lookups_req'=>$lookups_req]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       // return $request;
        post::create($request->only(['title','body','fb_link','end_date','location_id','field_of_study_id','study_level_id','english_requirment_id','abroad']));
        return $this->index();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(post $post)
    {
        $post=post::with(['location','english','field','level'])->where('id',$post->id)->get()[0];
      //  return $post;
        return response()->view('post\show',['post'=>$post]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(post $post)
    {
        //$post1=post::find($post);
        //return $post;
        return response()->view('post\edit',['post'=>$post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, post $post)
    {
        $post->update($request->all());
        return $this->index();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(post $post)
    {
        $post->delete();
        return $this->index();
    }

    public function display()
    {
        $posts=post::paginate(8);
        return response()->view('post\postdisplay',['posts'=>$posts]);
    }
}

winscholarship/resources/views/_layout/footer.blade.php
<div class="row fixed-bottom" style="height:10%;background-color:#a0eab1;">
    <div class="col-12">
    <p dir="ltr" style="margin-left:1%;margin-top:1%;font-size:1.7em;color:red;dispaly:inline;"><a href
    ="http://www.brontosoft.com">
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp2019-Now</a></p>
    
    </div>
</div>

winscholarship/resources/views/_layout/header.blade.php
<script src="{{asset(''.'js/jquery-3.4.1.min.js')}}"></script>
<link href = {{ asset("css/bootstrap.css") }} rel="stylesheet" />

<div class="row" style="height:10%;background-color:#009000;border:solid white 2px;">
    <div class="col-12">

    <h2 class="display-3" style="color:white;text-shadow: 0 0 3px #FFFAFA, 0 0 5px #FFFAFA;">TitleOne<i class="fa fa-graduation-cap"></i></h2>
    
    </div>
</div>

winscholarship/resources/views/lookups/add.blade.php
@include('_layout.header')




<div class="row">
<div class="col-12">
<div class="container">

<form class="form-group" method="POST" action="../lookups" >
@csrf

<label>name</label>
<input type="text" class="form-control" name="name"><br>

<input hidden type="text" name="cat_id">
<label>Cat</label>
<select>
<option  value="null">null</option>

  @foreach($lookups_cat as $lookup)
  <option class="cat_id_option"  value="{{$lookup->id}}">{{$lookup->name}}</option>
  @endforeach
</select>

<input hidden type="text" name="parent_id">
<label>Parent</label>
<select >
<option  value="null">null</option>
  @foreach($lookups as $lookup)
  <option class="parent_id_option" value="{{$lookup->id}}">{{$lookup->name}}</option>
  @endforeach
</select>

<br>
<input type="submit" >

</form>

</div>
</div>
</div>
@include('_layout.footer')

winscholarship/resources/views/lookups/edit.blade.php
@include('_layout.header')
<div class="row">
<div class="col-12">
<div class="container">

<form class="form-group" method="POST" action="{{route('post.update',['id'=>$post->id])}}" >
@csrf
{{ method_field('PATCH') }}
<label>Post Title</label>

<input type="text" name="title" class="form-control" value="{{$post->title}}"><br>
<label>Body</label>
<textarea type="text" name="body" class="form-control" value="{{$post->body}}">{{$post->body}} </textarea> <br>
<label>Facebook Link</label>
<input type="text" name="fb_link" class="form-control"  value="{{$post->fb_link}}"><br>
<label>End Date</label>
<input type="date" name="end_date" class="form-control" value="{{$post->expiry}}"><br>
<input type="file"  class="form-control" name="post_photo"><br>
<br>
<input type="submit" >
</form>

</div>
</div>
</div>
@include('_layout.footer')

winscholarship/resources/views/lookups/postdisplay.blade.php
@include('_layout.header')

@foreach($posts as $post)

    <h1>{{$post->title}}</h1>
    <p>{{$post->body}}</p>

@endforeach
                        <ul class="pagination">
                          @for ($i = 1; $i <= $posts->lastPage(); $i++)
                            <li  @if($posts->currentPage() == $i) class="active" @endif><span>{{ $i }}</span></li>
                          @endfor
                        </ul>

@include('_layout.footer')

winscholarship/resources/views/lookups/show.blade.php
@include('_layout.header')

<div dir="rtl" lang="ar" class="container">
<div class="artical">
<h1 style='display:inline;' >{{$post->title}}</h1>
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<p style="display:inline;color:red">Application Last Date &nbsp <strong>{{$post->expiry}}</strong></p><br>

<br>
<br>
<a href="{{$post->fb_link}}">FB Link</a>

<br>
<br>
<br>

<p>{{$post->body}}</p>
<div>
</div>
@include('_layout.footer')

<style>

.artical
{
    text-align:right;
}
.artical p {
    text-align: justify;
  text-justify: inter-word;
}

</style>

winscholarship/resources/views/lookups/table.blade.php
@include('_layout.header')

<div class="row" style="margin-top:5%;">
<div class="col-12">
<table class="table">
<tr>
<th>Title</th>
<th>Body</th>
<th>FB Link</th>
<th>Actions</th>
<tr>
@foreach($post as $pst)
<tr>
<td>{{$pst->title}}</td>
<td>{{substr($pst->body,0,200)}}</td>
<td>{{$pst->fb_link}}</td>
<td>
<a href="{{asset('').'post/'.$pst->id}}"><button class="btn btn-primary">Show</button><a/>&nbsp&nbsp
<a href="{{asset('').'post/'.$pst->id.'/edit'}}"><button class="btn btn-info">Edit</button><a/>&nbsp
<form method="POST" style="display:inline" action="{{route('post.destroy',['id'=>$pst->id])}}">
@csrf
{{ method_field('DELETE') }}

<input class="btn btn-danger" type="submit" value="Delete" name="delete">
</form>
</td>
</tr>
@endforeach
</table>
</div>
</div>
@include('_layout.footer')

winscholarship/resources/views/post/add.blade.php
<div class="container-fluid">
@include('_layout.header')




<div class="row" style="padding:1%">
<div class="container">

<form class="form-group" method="POST" action="../post" >
@csrf

<label>Title</label>
<input type="text" class="form-control" name="title"><br>
<label>Body</label>
<textarea type="text" class="form-control" name="body"></textarea><br>
<label>Facebook Link</label>
<input type="text" class="form-control" name="fb_link"><br>


<div class="col-12">
        <div class="row">

                  <div>
                      <input class="hiddeninput"  hidden type="text" value="location" name="location_id">
                      <label>Location</label>
                      <select class="form-control">
                      <option class="form-control" value="null">null</option>
                        @foreach($lookups_loc as $lookup)
                        <option    value="{{$lookup->id}}">{{$lookup->name}}</option>
                        @endforeach
                      </select>

                  </div>
                  <div>
                        <input class="hiddeninput" hidden type="text" value="Field"  name="field_of_study_id">
                        <label>Field of Study</label>
                        <select class="form-control">
                        <option  class="form-control" value="null">null</option>
                          @foreach($lookups_field as $lookup)
                          <option  value="{{$lookup->id}}">{{$lookup->name}}</option>
                          @endforeach
                        </select>

                  </div>
                  <div>

                          <input hidden type="text" value="Level" name="study_level_id">
                          <label>Study Level ID</label>
                          <select class="form-control">
                          <option class="form-control" value="null">null</option>
                            @foreach($lookups_level as $lookup)
                            <option   value="{{$lookup->id}}">{{$lookup->name}}</option>
                            @endforeach
                          </select>

                  </div>
                  <div>

                        <input hidden value="English" type="text" name="english_requirment_id">
                        <label>English Requirment</label>
                        <select class="form-control">
                        <option class="form-control" value="null">null</option>
                          @foreach($lookups_req as $lookup)
                          <option   value="{{$lookup->id}}">{{$lookup->name}}</option>
                          @endforeach
                        </select>
                        <br>

                  </div>
                  <div>
                        <input hidden type="text" value="Abroad" name="abroad">
                        <label>Is Abroad</label>
                        <select class="form-control">
                        <option class="form-control" value="1">YES</option>
                        <option class="form-control" value="0">NO</option>
                        </select>
                  </div>
        </div>

</div>


<label>End Date</label>
<input type="date" class="form-control" name="end_date"><br>
<input type="file" class="form-control" name="post_photo"><br>
<br>
<input type="submit" >
</form>

</div>
</div>
</div>

<script>
$('select').change(function(){ $(this).closest('div').find('input').val($(this).val()); console.log($(this).closest('div').find('input').val());});
</script>
@include('_layout.footer')
</div>

winscholarship/resources/views/post/edit.blade.php
@include('_layout.header')
<div class="row">
<div class="col-12">
<div class="container">

<form class="form-group" method="POST" action="{{route('post.update',['id'=>$post->id])}}" >
@csrf
{{ method_field('PATCH') }}
<label>Post Title</label>

<input type="text" name="title" class="form-control" value="{{$post->title}}"><br>
<label>Body</label>
<textarea type="text" name="body" class="form-control" value="{{$post->body}}">{{$post->body}} </textarea> <br>
<label>Facebook Link</label>
<input type="text" name="fb_link" class="form-control"  value="{{$post->fb_link}}"><br>
<label>End Date</label>
<input type="date" name="end_date" class="form-control" value="{{$post->end_date}}"><br>
<input type="file"  class="form-control" name="post_photo"><br>
<br>
<input type="submit" >
</form>

</div>
</div>
</div>
@include('_layout.footer')

winscholarship/resources/views/post/postdisplay.blade.php
<div class="container-fluid">
@include('_layout.header')
<div class="row" style="padding:2%">
<div class="row" >
@foreach($posts as $post)
<div class="col-3">
    <img src="{{asset('').'photos/post.jpg'}}" height="20%"; width="100%;">
    <h1>{{$post->title}}</h1>
    <p>{{substr($post->body,0,100)}}....</p>
    <a href="{{asset('').'post/'.$post->id}}"><button class="btn btn-primary">Read</button></a><br><br>

</div>


@endforeach
</div>


<div class="row">


<div>
    {!!   $posts->links() !!}
</div>

</div>
</div>

@include('_layout.footer')
</div>

winscholarship/resources/views/post/show.blade.php
@include('_layout.header')

<div dir="rtl" lang="ar" class="container">
<div class="artical">
<h1 style='display:inline;' >{{$post->title}}</h1>
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<br>
<label dir="rtl" style="display:inline"><strong>Location</strong></label>&nbsp&nbsp&nbsp<p dir="rtl" style="display:inline">{{$post->location->name ?? "."}}</p><br>
<label style="display:inline" ><strong>English</strong></label>&nbsp&nbsp&nbsp<p style="display:inline">{{$post->english->name ?? "." }}</p><br>
<label style="display:inline" ><strong>Field</strong></label>&nbsp&nbsp&nbsp<p style="display:inline">{{$post->field->name ?? "." }}</p><br>
<label style="display:inline" ><strong>level</strong></label>&nbsp&nbsp&nbsp<p style="display:inline" >{{$post->level->name ?? "." }}</p><br>

<p style="display:inline;color:red">Application Last Date &nbsp <strong>{{$post->end_date}}</strong></p><br>

<br>
<br>
<a href="{{$post->fb_link}}">FB Link</a>

<br>
<br>
<br>

<p>{{$post->body}}</p>
</div>
</div>
@include('_layout.footer')

<style>

.artical
{
    text-align:right;
}
.artical p {
    text-align: justify;
  text-justify: inter-word;
}

</style>

winscholarship/resources/views/post/table.blade.php
@include('_layout.header')

<div class="row" style="margin-top:5%;">
<div class="col-12">
<table class="table">
<tr>
<th>Title</th>
<th>Body</th>
<th>FB Link</th>
<th>Actions</th>
<tr>
@foreach($post as $pst)
<tr>
<td>{{$pst->title}}</td>
<td>{{substr($pst->body,0,200)}}</td>
<td>{{$pst->fb_link}}</td>
<td>
<a href="{{asset('').'post/'.$pst->id}}"><button class="btn btn-primary">Show</button><a/>&nbsp&nbsp
<a href="{{asset('').'post/'.$pst->id.'/edit'}}"><button class="btn btn-info">Edit</button><a/>&nbsp
<form method="POST" style="display:inline" action="{{route('post.destroy',['id'=>$pst->id])}}">
@csrf
{{ method_field('DELETE') }}

<input class="btn btn-danger" type="submit" value="Delete" name="delete">
</form>
</td>
</tr>
@endforeach
</table>
</div>
</div>
@include('_layout.footer')